POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Clark Kent",
  "email": "clark@email.com",
  "referrer": "025105a2-389e-4c82-bfdb-5ab439db3e0e"
}

###

GET http://localhost:3333/invites/025105a2-389e-4c82-bfdb-5ab439db3e0e

###

GET http://localhost:3333/subscribers/025105a2-389e-4c82-bfdb-5ab439db3e0e/ranking/clicks

###

GET http://localhost:3333/subscribers/025105a2-389e-4c82-bfdb-5ab439db3e0e/ranking/count

###

GET http://localhost:3333/subscribers/025105a2-389e-4c82-bfdb-5ab439db3e0e/ranking/position
